-- usuwanie obiektów jeœli ju¿ by³y...

DROP VIEW V_HRDOCS_INFO
GO

-- tworzenie obiektów

CREATE VIEW V_HRDOCS_INFO AS
SELECT 
/*-- odkomentowaæ na bazie testowej */
	1 AS ID,
	'NAZWISKO' AS NAZWISKO,
	'IMIE' AS IMIE,
	1 AS URLOP_ZALEGLY,
	2 AS URLOP_NALEZNY,
	3 AS URLOP_WYKORZYSTANY,
	4 AS URLOP_POZOSTALY,
	5 AS URLOP_OPIEK,
	'2000-01-01' AS DOW_OSOB_DATA_WAZ,
	'2000-01-02'  AS PASZPORT_DATA_WAZ,
	'M_MIASTO' AS ADRESM_MIASTO,
	'M_ULICA' AS ADRESM_ULICA,
	'M_NR_DOMU' AS ADRESM_NR_DOMU,
	'M_NR_MIESZ' AS ADRESM_NR_MIESZ,
	'Z_MIASTO' AS ADRESZ_MIASTO,
	'Z_ULICA' AS ADRESZ_ULICA,
	'Z_NR_DOMU' AS ADRESZ_NR_DOMU,
	'Z_NR_MIESZ' AS ADRESZ_NR_MIESZ,
	'TELEFON' AS TELEFON,
	'US' AS URZAD_SKARB,
	'RB' AS RACHUNEK_BANK,
	'2000-01-03'  AS BADANIA_DATA_WAZ,
	'NIP' AS NIP,
	'PESEL' AS PESEL
/**/
/*-- odkomentowaæ na bazie docelowej
	e.EMPLID AS ID,
	e.PPLNAME AS NAZWISKO,
	e.PPLFIRSTNAME AS IMIE,
	e.PPLLEAVEPREVYEARDAYS AS URLOP_ZALEGLY,
	e.PPLLEAVEOWINGDAYS AS URLOP_NALEZNY,
	e.PPLLEAVEUSEDDAYS AS URLOP_WYKORZYSTANY,
	e.PPLLEAVEREMAININGDAYS AS URLOP_POZOSTALY,
	cs.DAYS AS URLOP_OPIEK,
	cast(e.PPLIDCARDEXPIRYDATE as DATE) AS DOW_OSOB_DATA_WAZ,
	cast(e.PPLPassportExpiryDate as DATE) AS PASZPORT_DATA_WAZ,
	a1.CITY AS ADRESM_MIASTO,
	a1.STREET AS ADRESM_ULICA,
	a1.HOUSE AS ADRESM_NR_DOMU,
	a1.FLAT AS ADRESM_NR_MIESZ,
	a0.CITY AS ADRESZ_MIASTO,
	a0.STREET AS ADRESZ_ULICA,
	a0.HOUSE AS ADRESZ_NR_DOMU,
	a0.FLAT AS ADRESZ_NR_MIESZ,
	a0.CELLULARPHONE AS TELEFON,
	t.NAME AS URZAD_SKARB,
	e.PPLACCOUNTNO AS RACHUNEK_BANK,
	cast(ex1.EXPIRYDATE as DATE) AS BADANIA_DATA_WAZ,
	e.PPLTAXNUMBER AS NIP,
	e.PPLPESEL AS PESEL
FROM ILF_DAX09_PRD.dbo.EMPLTABLE e
--zameldowania
LEFT OUTER JOIN ILF_DAX09_PRD.dbo.PPLADDRESS a0 ON a0.EMPLID = e.EMPLID and a0.ADDRESSCLASSIFICATION = 0 and a0.ADDRESSTABLE = 0 and a0.DATAAREAID = e.DATAAREAID
--zamieszkania
LEFT OUTER JOIN ILF_DAX09_PRD.dbo.PPLADDRESS a1 ON a1.EMPLID = e.EMPLID and a1.ADDRESSCLASSIFICATION = 1 and a1.ADDRESSTABLE = 0 and a1.DATAAREAID = e.DATAAREAID
--Urzad skarbowy
LEFT OUTER JOIN ILF_DAX09_PRD.dbo.PPLTAXOFFICETABLE t ON t.TAXOFFICEID = e.PPLTAXOFFICE AND t.DATAAREAID = e.DATAAREAID
--przyslugujacy urlop opiekunczy
LEFT OUTER JOIN ILF_DAX09_PRD.dbo.PPLEMPLCARESTATEMENT cs ON cs.EMPLID = e.EMPLID AND cs.DATAAREAID = e.DATAAREAID AND cs.YEAR = YEAR(GETDATE())
--badania okresowe
LEFT OUTER JOIN 
	(SELECT ex.EMPLID, ex.DATAAREAID, MAX(ex.EXPIRYDATE) as EXPIRYDATE FROM ILF_DAX09_PRD.dbo.PPLEMPLPERIODICEXAMINATION ex
		WHERE ex.EXAMINATIONID = 1
		GROUP BY ex.EMPLID, ex.DATAAREAID) ex1  on e.EMPLID = ex1.EMPLID and ex1.DATAAREAID = e.DATAAREAID
WHERE e.DATAAREAID = 'ilf'
  --AND e.EMPLID = ''

*/
GO

GRANT SELECT ON V_HRDOCS_INFO TO HRDOCS -- HRDOCS to uzytkownik który jest na potrzeby aplikacji HRDOCS, nadajemy uprawnienie do odczytu z tego widoku
GO
