ALTER TABLE T_Documents ADD CONSTRAINT PK_Documents PRIMARY KEY CLUSTERED (ID);
GO
ALTER TABLE T_Documents ADD CONSTRAINT UQ_Documents_01 UNIQUE (PESEL, DateYear, DateMonth, DocumentsLoadID);
GO
ALTER TABLE T_Documents ADD	CONSTRAINT FK_Documents_01 FOREIGN KEY (DocumentsLoadID) REFERENCES T_DocumentsLoads(ID);
GO
ALTER TABLE T_Documents ADD CONSTRAINT CK_Documents_01 CHECK (DateYear BETWEEN 2000 AND 9999);
GO
ALTER TABLE T_Documents ADD CONSTRAINT CK_Documents_02 CHECK (DateMonth BETWEEN 1 AND 12);
GO
