ALTER TABLE T_Employees ADD CONSTRAINT PK_Employees PRIMARY KEY CLUSTERED (ID);
GO
ALTER TABLE T_Employees ADD CONSTRAINT UQ_Employees_01 UNIQUE (PESEL);
GO
ALTER TABLE T_Employees ADD CONSTRAINT UQ_Employees_02 UNIQUE (Identifier);
GO
